image: "python:3.7"

before_script:
  - python --version
  - pip install pylint --quiet

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pylint --ignored-classes=_socketobject *.py
