image: "python:3.7"

before_script:
  - apt update -qq && apt install -y -qq libxslt-dev unixodbc-dev tdsodbc libopenjp2-7 sqlite3
  - python --version
  - pip3 install -r requirements.txt
  - pip3 install pylint-fail-under --quiet

stages:
  - Static Analysis Part 1
  - Static Analysis Part 2
  - Hilding unittest


relaxed_pylint_analysis:
  stage: Static Analysis Part 1
  allow_failure: true
  script:
  - find ./test_folder/on_the_fly_test/ -type f -name "*.py" | xargs pylint -d duplicate-code,import-error,invalid-name || true

strict_pylint_analysis:
  stage: Static Analysis Part 2
  allow_failure: false
  script:
  - find ./hilding/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 -d duplicate-code,import-error,invalid-name
  - find ./supportfunctions/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 -d duplicate-code,import-error,invalid-name
  - find ./test_folder/automated/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 --module-rgx="BSW_REQPROD_\d*_.*|e_\d*_(\w*|-)_\d*_.*" -d duplicate-code,import-error,no-name-in-module
  - find ./test_folder/manual/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 --module-rgx="BSW_REQPROD_\d*_.*|e_\d*_(\w*|-)_\d*_.*" -d duplicate-code,import-error,no-name-in-module
#  - find ./test_folder/not_applicable/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 --module-rgx="BSW_REQPROD_\d*_.*" -d duplicate-code,import-error,no-name-in-module
  - find ./test_folder/on_the_fly_test/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 -d duplicate-code,import-error,no-name-in-module,invalid-name

hilding_unittest:
  stage: Hilding unittest
  allow_failure: false
  script:
    - pytest ./hilding/
