image: "python:3.7"

before_script:
  - python --version
  - pip3 install pylint --quiet
  - pip3 install openpyxl --quiet
  - pip3 install lxml --quiet
  - pip3 install pylint-fail-under --quiet

stages:
  - Static Analysis Part 1
  - Static Analysis Part 2


relaxed_pylint_analysis:
  stage: Static Analysis Part 1
  allow_failure: true
  script:
  - find ./Implement_MEP2_Support_EOL_def/ -type f -name "*.py" | xargs pylint -d R0801 || true
  - find ./Py_testenv/ -type f -name "*.py" | xargs pylint -d R0801 || true
  - find ./test_cases_old/ -type f -name "*.py" | xargs pylint --module-rgx="BSW_REQPROD_\d*_.*" -d R0801 || true
  - find ./test_cases/ -type f -name "*.py" | xargs pylint --module-rgx="BSW_REQPROD_\d*_.*" -d R0801 || true

strict_pylint_analysis:
  stage: Static Analysis Part 2
  allow_failure: false
  script:
  - find ./autotest/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 -d R0801
  - find ./manual_test/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 --module-rgx="BSW_REQPROD_\d*_.*" -d R0801
  #- find ./test_cases/ -type f -name "*.py" | xargs pylint-fail-under --fail_under 10.0 --module-rgx="BSW_REQPROD_\d*_.*" -d R0801
