image: "python:3.7"

before_script:
  - python --version
  - pip3 install pylint --quiet
  - pip3 install openpyxl --quiet
  - pip3 install lxml --quiet

stages:
  - Static Analysis

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - find ./autotest/ -type f -name "*.py" | xargs pylint || true
  - find ./Py_testenv/ -type f -name "*.py" | xargs pylint || true
  - find ./testscripts/ -type f -name "*.py" | xargs pylint || true
  - python3 -m pylint --disable=duplicate-code