echo on
set TESTREPO=%USERPROFILE%\Repos\odtb2pilot
set ODTBPROJ=ihfa_v436
set ODTBPROJPARAM=%TESTREPO%\projects\%ODTBPROJ%
set PYTHONPATH=%TESTREPO%;%ODTBPROJPARAM%;%cd%

echo TESTREPO=%TESTREPO%
echo ODTBPROJ=%ODTBPROJ%
echo ODTBPROJPARAM=%ODTBPROJPARAM%
