hvbm_p519:
    run:
        did_list_range : [[EDA0,EDFF],[ED20,ED7F]]

ecm_phev:
    run:
        did_list_range : [[EDA0,EDFF],[ED20,ED7F]]

ecm_hp:
    run:
        did_list_range : [[EDA0,EDFF],[ED20,ED7F]]

ecm_lp:
    run:
        did_list_range : [[EDA0,EDFF],[ED20,ED7F]]
