echo on
set TESTREPO=%USERPROFILE%\Repos\odtb2pilot
set ODTBPROJ=my_project_to_use
set ODTBPROJPARAM=%TESTREPO%\projects\%ODTBPROJ%
set PYTHONPATH=%TESTREPO%;%ODTBPROJPARAM%;%cd%

echo TESTREPO=%TESTREPO%
echo ODTBPROJ=%ODTBPROJ%
echo ODTBPROJPARAM=%ODTBPROJPARAM%
