# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protogenerated.common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_api.proto',
  package='base',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10system_api.proto\x12\x04\x62\x61se\x1a\x0c\x63ommon.proto2w\n\rSystemService\x12\x36\n\x10GetConfiguration\x12\x0b.base.Empty\x1a\x13.base.Configuration\"\x00\x12.\n\x0bListSignals\x12\x0f.base.NameSpace\x1a\x0c.base.Frames\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SYSTEMSERVICE = _descriptor.ServiceDescriptor(
  name='SystemService',
  full_name='base.SystemService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=40,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConfiguration',
    full_name='base.SystemService.GetConfiguration',
    index=0,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._CONFIGURATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListSignals',
    full_name='base.SystemService.ListSignals',
    index=1,
    containing_service=None,
    input_type=common__pb2._NAMESPACE,
    output_type=common__pb2._FRAMES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SYSTEMSERVICE)

DESCRIPTOR.services_by_name['SystemService'] = _SYSTEMSERVICE

# @@protoc_insertion_point(module_scope)
