echo on
set TESTREPO=%USERPROFILE%\Repos\odtb2pilot
set ODTBPROJ=hvbm_p519_sa1
set ODTBPROJPARAM=%TESTREPO%\projects\%ODTBPROJ%
set PYTHONPATH=%TESTREPO%;%ODTBPROJPARAM%;%cd%

echo TESTREPO=%TESTREPO%
echo ODTBPROJ=%ODTBPROJ%
echo ODTBPROJPARAM=%ODTBPROJPARAM%
